---
title: Steve’s Story
timezone: UTC
collections:
  events:
    title: Events
    output: true
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: events
  values:
    layout: event
email: asdf@domain.com
description: |
  Family man and loyal friend Steve lived an active life until being diagnosed with Primary Progressive Multiple Sclerosis at the age of 50.
  Now he's attempting to raise £50,000 for a pioneering treatment to stop the MS in its tracks.
baseurl: 
url: http://stevesstory.co.uk
twitter_username: example
facebook_username: example
markdown: kramdown
future: true
supporter_list:
- Arrabelle's
- Beau's Hairdressing
- Caroline & Co
- Christopher Hayes Barber
- Double Tree Hilton Chester
- Fake It Hair & Beauty
- Eyes Lash Love
- Fitness First
- Glamour Dolls
- Jade Mutch Makeovers
- Jo Jacques
- MadeUp
- Matalan Bromborough
- Matalan Birkenhead
- Ms Flamingo
- Muffs Butchers
- Liverpool Football Club
- The Royal Oak Hungry Horse
- Oval Ski Club
- Port Sunlight Rugby Club
- Rock Ferry Primary School
- Sale Rugby Club
- The Bromborough Hotel
- Sinfully Delightful
- Unique Hair
- Ward's Fish
- Waterstones
- West Coast Mainline – Virgin Trains
- Zuger's
- Nathaniel's Brombrough
- Acorn, Bebington
