# Site settings

title: Steve’s Story # Title of your site
email: asdf@domain.com # Your contant email

description: >
  Family man and loyal friend Steve lived an active life until being diagnosed with Primary Progressive Multiple Sclerosis at the age of 50.

  Now he's attempting to raise £50,000 for a pioneering treatment to stop the MS in its tracks.

baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://stevesstory.co.uk" # the base hostname & protocol for your site

# Social links.
# Replace the word 'example' with your username if you want to include the icon in the left sidebar
# Delete the word 'example' if you don't want to include the icon in the left sidebar

twitter_username:     example  # Replace this with your Twitter username
facebook_username:    example  # Replace this with your Facebook username

# Build settings
markdown: kramdown
