---
title: Steve’s Story
timezone: UTC
collections:
  events:
    title: Events
    output: true
  posts:
    title: Posts
    output: true
  something:
    title: Something
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "events" # previously `post` in Jekyll 2.2.
    values:
      layout: "event"
email: asdf@domain.com
description: |
  Family man and loyal friend Steve lived an active life until being diagnosed with Primary Progressive Multiple Sclerosis at the age of 50.
  Now he's attempting to raise £50,000 for a pioneering treatment to stop the MS in its tracks.
baseurl: ''
url: http://stevesstory.co.uk
twitter_username: example
facebook_username: example
markdown: kramdown
