---
title: Steve’s Story
timezone: UTC
collections:
  events:
    title: Events
    output: true
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: events
  values:
    layout: event
email: asdf@domain.com
description: |
  Family man and loyal friend Steve lived an active life until being diagnosed with Primary Progressive Multiple Sclerosis at the age of 50.
  Now he's attempting to raise £50,000 for a pioneering treatment to stop the MS in its tracks.
baseurl: 
url: http://stevesstory.co.uk
twitter_username: example
facebook_username: example
markdown: kramdown
future: true
supporter_list:
- Acorn, Bebington
- Amber Pimlott
- Arrabelle's
- Beau's Hairdressing
- Blenheim Palace
- Caroline & Co
- Chester Race Course
- Christopher Hayes Barber
- Double Tree Hilton Chester
- Fake It Hair & Beauty
- Eyes Lash Love
- Fitness First
- Glamour Dolls
- Harties Crafts
- Heswall Barber
- House of Hair
- Imagine Hair Salon
- Jade Mutch Makeovers
- Jo Jacques
- Knit & Knatter
- Liverpool Football Club
- MadeUp
- Matalan Bromborough
- Matalan Birkenhead
- Ms Flamingo
- Muffs Butchers
- Nathaniel's Brombrough
- Odeon, Bromborugh
- Oval Ski Club
- Paul Kay Hair Salon
- Pesto at the Dibbi
- Port Sunlight Rugby Club
- Punchbowl B&B Woodstock
- Rock Ferry Primary School
- The Royal Oak Hungry Horse
- Sale Rugby Club
- Sian Sword
- The Bromborough Hotel
- Sinfully Delightful
- Unique Hair
- Ward's Fish
- Waterstones
- West Coast Mainline – Virgin Trains
- Willaston Barber
- Woodcote Hotel
- Wordles
- Zeros
- Zuger's
- Cammel Lairds
- Welsh Highland Railway
- Bromborough Paints
- Leverhulme Hotel
- Everton Football Club
- Hair by Dominique
- La Belle Epoque
- The Jewellery Box Wirral
- Village Hotel Bromborough
